
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      dockerfile: ./Dockerfile.production
    image: slavazhuck/js-fastify-blog
    command: make test
#    env_file:
#      - .env
    environment:
        - DATABASE_HOST=${DATABASE_HOST-db}
        - DATABASE_NAME=${DATABASE_NAME-postgres}
        - DATABASE_USERNAME=${DATABASE_USERNAME-postgres}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD-password}
        - DATABASE_PORT=${DATABASE_PORT-5432}
    depends_on:
      db:
        condition: service_healthy
      #- healthcheck

      
  db:
    image: postgres:16-alpine
    restart: always
    environment:
        - POSTGRES_DB=${DATABASE_NAME-postgres}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD-password}
        - POSTGRES_USER=${DATABASE_USERNAME-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  
      
volumes:
  pgdata:
